[project]
name = "snc2fst"
version = "0.1.0"
description = "Compiles Search-and-Change grammars to OpenFST transducers."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.7.0",
    "tqdm>=4.66.0",
    "typer>=0.12.0",
]

[project.optional-dependencies]
dev = [
    "black>=24.0.0",
    "pytest>=8.0.0",
]

[tool.black]
line-length = 79

[project.scripts]
snc2fst = "snc2fst.main:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
